/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ChefIndexRouteImport } from './routes/chef.index'
import { Route as ChefDashboardRouteImport } from './routes/chef.dashboard'
import { Route as ChefRequestsRouteImport } from './routes/chef.requests'
import { Route as ChefStockRouteImport } from './routes/chef.stock'
import { Route as ChefWasteRouteImport } from './routes/chef.waste'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as ManagerOrdersRouteImport } from './routes/manager.orders'
import { Route as OrderTableIdRouteImport } from './routes/order.$tableId'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerExpensesRouteImport } from './routes/owner.expenses'
import { Route as OwnerMenuRouteImport } from './routes/owner.menu'
import { Route as OwnerOperationsRouteImport } from './routes/owner.operations'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as OwnerPurchasesRouteImport } from './routes/owner.purchases'
import { Route as OwnerReportsRouteImport } from './routes/owner.reports'
import { Route as OwnerRequestsRouteImport } from './routes/owner.requests'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerStaffRouteImport } from './routes/owner.staff'
import { Route as OwnerStockRouteImport } from './routes/owner.stock'
import { Route as OwnerTablesRouteImport } from './routes/owner.tables'
import { Route as OwnerWasteRouteImport } from './routes/owner.waste'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefIndexRoute = ChefIndexRouteImport.update({
  id: '/chef/',
  path: '/chef/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefDashboardRoute = ChefDashboardRouteImport.update({
  id: '/chef/dashboard',
  path: '/chef/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRequestsRoute = ChefRequestsRouteImport.update({
  id: '/chef/requests',
  path: '/chef/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefStockRoute = ChefStockRouteImport.update({
  id: '/chef/stock',
  path: '/chef/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefWasteRoute = ChefWasteRouteImport.update({
  id: '/chef/waste',
  path: '/chef/waste',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerOrdersRoute = ManagerOrdersRouteImport.update({
  id: '/manager/orders',
  path: '/manager/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTableIdRoute = OrderTableIdRouteImport.update({
  id: '/order/$tableId',
  path: '/order/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerExpensesRoute = OwnerExpensesRouteImport.update({
  id: '/owner/expenses',
  path: '/owner/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMenuRoute = OwnerMenuRouteImport.update({
  id: '/owner/menu',
  path: '/owner/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOperationsRoute = OwnerOperationsRouteImport.update({
  id: '/owner/operations',
  path: '/owner/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/owner/orders',
  path: '/owner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPurchasesRoute = OwnerPurchasesRouteImport.update({
  id: '/owner/purchases',
  path: '/owner/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRequestsRoute = OwnerRequestsRouteImport.update({
  id: '/owner/requests',
  path: '/owner/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStaffRoute = OwnerStaffRouteImport.update({
  id: '/owner/staff',
  path: '/owner/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStockRoute = OwnerStockRouteImport.update({
  id: '/owner/stock',
  path: '/owner/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTablesRoute = OwnerTablesRouteImport.update({
  id: '/owner/tables',
  path: '/owner/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerWasteRoute = OwnerWasteRouteImport.update({
  id: '/owner/waste',
  path: '/owner/waste',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chef/requests': typeof ChefRequestsRoute
  '/chef/stock': typeof ChefStockRoute
  '/chef/waste': typeof ChefWasteRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/orders': typeof ManagerOrdersRoute
  '/order/$tableId': typeof OrderTableIdRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/expenses': typeof OwnerExpensesRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/operations': typeof OwnerOperationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/purchases': typeof OwnerPurchasesRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/stock': typeof OwnerStockRoute
  '/owner/tables': typeof OwnerTablesRoute
  '/owner/waste': typeof OwnerWasteRoute
  '/chef/': typeof ChefIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chef/requests': typeof ChefRequestsRoute
  '/chef/stock': typeof ChefStockRoute
  '/chef/waste': typeof ChefWasteRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/orders': typeof ManagerOrdersRoute
  '/order/$tableId': typeof OrderTableIdRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/expenses': typeof OwnerExpensesRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/operations': typeof OwnerOperationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/purchases': typeof OwnerPurchasesRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/stock': typeof OwnerStockRoute
  '/owner/tables': typeof OwnerTablesRoute
  '/owner/waste': typeof OwnerWasteRoute
  '/chef': typeof ChefIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chef/requests': typeof ChefRequestsRoute
  '/chef/stock': typeof ChefStockRoute
  '/chef/waste': typeof ChefWasteRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/orders': typeof ManagerOrdersRoute
  '/order/$tableId': typeof OrderTableIdRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/expenses': typeof OwnerExpensesRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/operations': typeof OwnerOperationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/purchases': typeof OwnerPurchasesRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/stock': typeof OwnerStockRoute
  '/owner/tables': typeof OwnerTablesRoute
  '/owner/waste': typeof OwnerWasteRoute
  '/chef/': typeof ChefIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/staff'
    | '/chef/dashboard'
    | '/chef/requests'
    | '/chef/stock'
    | '/chef/waste'
    | '/manager/dashboard'
    | '/manager/orders'
    | '/order/$tableId'
    | '/owner/dashboard'
    | '/owner/expenses'
    | '/owner/menu'
    | '/owner/operations'
    | '/owner/orders'
    | '/owner/purchases'
    | '/owner/reports'
    | '/owner/requests'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/stock'
    | '/owner/tables'
    | '/owner/waste'
    | '/chef/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/staff'
    | '/chef/dashboard'
    | '/chef/requests'
    | '/chef/stock'
    | '/chef/waste'
    | '/manager/dashboard'
    | '/manager/orders'
    | '/order/$tableId'
    | '/owner/dashboard'
    | '/owner/expenses'
    | '/owner/menu'
    | '/owner/operations'
    | '/owner/orders'
    | '/owner/purchases'
    | '/owner/reports'
    | '/owner/requests'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/stock'
    | '/owner/tables'
    | '/owner/waste'
    | '/chef'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/staff'
    | '/chef/dashboard'
    | '/chef/requests'
    | '/chef/stock'
    | '/chef/waste'
    | '/manager/dashboard'
    | '/manager/orders'
    | '/order/$tableId'
    | '/owner/dashboard'
    | '/owner/expenses'
    | '/owner/menu'
    | '/owner/operations'
    | '/owner/orders'
    | '/owner/purchases'
    | '/owner/reports'
    | '/owner/requests'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/stock'
    | '/owner/tables'
    | '/owner/waste'
    | '/chef/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  ChefDashboardRoute: typeof ChefDashboardRoute
  ChefRequestsRoute: typeof ChefRequestsRoute
  ChefStockRoute: typeof ChefStockRoute
  ChefWasteRoute: typeof ChefWasteRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerOrdersRoute: typeof ManagerOrdersRoute
  OrderTableIdRoute: typeof OrderTableIdRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerExpensesRoute: typeof OwnerExpensesRoute
  OwnerMenuRoute: typeof OwnerMenuRoute
  OwnerOperationsRoute: typeof OwnerOperationsRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerPurchasesRoute: typeof OwnerPurchasesRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerRequestsRoute: typeof OwnerRequestsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerStaffRoute: typeof OwnerStaffRoute
  OwnerStockRoute: typeof OwnerStockRoute
  OwnerTablesRoute: typeof OwnerTablesRoute
  OwnerWasteRoute: typeof OwnerWasteRoute
  ChefIndexRoute: typeof ChefIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/': {
      id: '/chef/'
      path: '/chef'
      fullPath: '/chef/'
      preLoaderRoute: typeof ChefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/dashboard': {
      id: '/chef/dashboard'
      path: '/chef/dashboard'
      fullPath: '/chef/dashboard'
      preLoaderRoute: typeof ChefDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/requests': {
      id: '/chef/requests'
      path: '/chef/requests'
      fullPath: '/chef/requests'
      preLoaderRoute: typeof ChefRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/stock': {
      id: '/chef/stock'
      path: '/chef/stock'
      fullPath: '/chef/stock'
      preLoaderRoute: typeof ChefStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/waste': {
      id: '/chef/waste'
      path: '/chef/waste'
      fullPath: '/chef/waste'
      preLoaderRoute: typeof ChefWasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/orders': {
      id: '/manager/orders'
      path: '/manager/orders'
      fullPath: '/manager/orders'
      preLoaderRoute: typeof ManagerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$tableId': {
      id: '/order/$tableId'
      path: '/order/$tableId'
      fullPath: '/order/$tableId'
      preLoaderRoute: typeof OrderTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/expenses': {
      id: '/owner/expenses'
      path: '/owner/expenses'
      fullPath: '/owner/expenses'
      preLoaderRoute: typeof OwnerExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/menu': {
      id: '/owner/menu'
      path: '/owner/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/operations': {
      id: '/owner/operations'
      path: '/owner/operations'
      fullPath: '/owner/operations'
      preLoaderRoute: typeof OwnerOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/owner/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/purchases': {
      id: '/owner/purchases'
      path: '/owner/purchases'
      fullPath: '/owner/purchases'
      preLoaderRoute: typeof OwnerPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/requests': {
      id: '/owner/requests'
      path: '/owner/requests'
      fullPath: '/owner/requests'
      preLoaderRoute: typeof OwnerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/staff': {
      id: '/owner/staff'
      path: '/owner/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof OwnerStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/stock': {
      id: '/owner/stock'
      path: '/owner/stock'
      fullPath: '/owner/stock'
      preLoaderRoute: typeof OwnerStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/tables': {
      id: '/owner/tables'
      path: '/owner/tables'
      fullPath: '/owner/tables'
      preLoaderRoute: typeof OwnerTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/waste': {
      id: '/owner/waste'
      path: '/owner/waste'
      fullPath: '/owner/waste'
      preLoaderRoute: typeof OwnerWasteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  ChefDashboardRoute: ChefDashboardRoute,
  ChefRequestsRoute: ChefRequestsRoute,
  ChefStockRoute: ChefStockRoute,
  ChefWasteRoute: ChefWasteRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerOrdersRoute: ManagerOrdersRoute,
  OrderTableIdRoute: OrderTableIdRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerExpensesRoute: OwnerExpensesRoute,
  OwnerMenuRoute: OwnerMenuRoute,
  OwnerOperationsRoute: OwnerOperationsRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerPurchasesRoute: OwnerPurchasesRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerRequestsRoute: OwnerRequestsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerStaffRoute: OwnerStaffRoute,
  OwnerStockRoute: OwnerStockRoute,
  OwnerTablesRoute: OwnerTablesRoute,
  OwnerWasteRoute: OwnerWasteRoute,
  ChefIndexRoute: ChefIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
